
language: groovy

sudo: required

before_script:
 - ./gradlew -S clean --console=plain

script:
 - ./gradlew -S -i --console=plain assemble
 - ./gradlew -S -i --console=plain --debug test
 - ./gradlew -S -i --console=plain integrationTest compatibilityTest

jdk:
 - oraclejdk8
# - oraclejdk7
# - openjdk7
# - openjdk6

os:
 - linux
# osx_image: xcode7.3

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
#after_success: ./gradlew coveralls -PbintrayUser= -PbintrayApiKey

branches:
  only:
    - master
    - development
#    - release
